! basic closure
exogenous
        afall
    afcom
    afreg
    afsec    
    ams
    aoall
    aoreg
    aosec
  ! atall               omitted
    atd
    atf
    atm
    ats
    au
    cgdslack
    dpgov
    dppriv
    dpsave
    endwslack
    incomeslack
    pemp
    pfactwld
    pop
    profitslack
    psaveslack
    qo(ENDW_COMM,REG)
    RCTAXB
  ! tf                  omitted
  ! tfd                 omitted
  ! tfm                 omitted
  ! tgd                 omitted
  ! tgm                 omitted
    tm
    tms
    to
  ! tpd                 omitted
  ! tpm                 omitted
    tp
    tradslack
    tx
    txs;
Rest Endogenous ;
